In [1]:
import numpy as np

In [3]:
arr = np.array([1,2,3,])
arr

array([1, 2, 3])

In [5]:
arr_2d = np.array([[1,2,3],[4,5,6]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [13]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [14]:
np.random.rand(3,2)

array([[0.17026887, 0.80669067],
       [0.90092957, 0.26228909],
       [0.38057099, 0.68674324]])

In [15]:
np.random.randn(3,2)

array([[ 1.08611738,  0.05884331],
       [-0.19417845, -0.79356255],
       [-0.22342628,  0.06749849]])

In [17]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape)

(2, 3)


In [18]:
print(arr.ndim)

2


In [19]:
print(arr.size)

6


In [20]:
print(arr.dtype)

int64


In [21]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a + b

array([5, 7, 9])

In [22]:
a * b

array([ 4, 10, 18])

In [23]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [24]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [25]:
a @ b

array([[19, 22],
       [43, 50]])

In [26]:
arr = np.array([1,2,3,4])
arr.sum()

np.int64(10)

In [27]:
arr.mean()

np.float64(2.5)

In [28]:
arr.max()

np.int64(4)

In [29]:
arr.min()

np.int64(1)

In [30]:
arr.std()

np.float64(1.118033988749895)

In [31]:
arr = np.array([1,2,3,4,5])
arr[0]

np.int64(1)

In [33]:
arr[1:4]

array([2, 3, 4])

In [34]:
arr[::2]

array([1, 3, 5])

In [35]:
arr = np.array([[1,2,3],[4,5,6]])
arr[0,1]


np.int64(2)

In [36]:
arr[:,1]

array([2, 5])

In [37]:
arr[1,:2]

array([4, 5])

In [39]:
arr = np.array([1, 2, 3, 4, 5])
mask = arr>3
arr[mask]

array([4, 5])

In [42]:
arr = np.arange(6)
arr

array([0, 1, 2, 3, 4, 5])

In [44]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [46]:
a = np.array([1,2])
b = np.array([3,4])
np.concatenate((a,b))

array([1, 2, 3, 4])

In [47]:
np.vstack((a,b))

array([[1, 2],
       [3, 4]])

In [48]:
np.hstack((a,b))

array([1, 2, 3, 4])

In [50]:
a = np.array([1,2,3])
a + 5 

array([6, 7, 8])

In [51]:
np.save('array.npy',arr)

In [52]:
loaded_arr = np.load('array.npy')